=== Wiwiweb/Starcraft-Boardgame/res/xmlSchemas/factions.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="factions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="faction" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="race" type="xs:string" />

							<xs:element name="base" type="xs:string" />

							<xs:element name="startingUnits">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="workers" type="xs:int" />
										<xs:element name="transports" type="xs:int" />
										<xs:element name="unit" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:int">
														<xs:attribute name="type" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />

					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

		<xs:unique name="uniqueName">
			<xs:selector xpath="faction" />
			<xs:field xpath="@name" />
		</xs:unique>

	</xs:element>
</xs:schema>

=== Wiwiweb/Starcraft-Boardgame/res/data/factions.xml
<?xml version="1.0" encoding="UTF-8"?>
<factions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xmlSchemas/factions.xsd">

	<faction name="Jim Raynor">
		<race>Terran</race>
		<base>Terran Base</base>
		<startingUnits>
			<workers>8</workers>
			<transports>1</transports>
			<unit type="Marine">2</unit>
			<unit type="Firebat">1</unit>
			<unit type="Vulture">1</unit>
		</startingUnits>
	</faction>

	<faction name="Arcturus Mengsk">
		<race>Terran</race>
		<base>Terran Base</base>
		<startingUnits>
			<workers>8</workers>
			<transports>1</transports>
			<unit type="Marine">2</unit>
			<unit type="Firebat">1</unit>
			<unit type="Ghost">1</unit>
		</startingUnits>
	</faction>

	<faction name="Overmind">
		<race>Zerg</race>

		<base>Zerg Base</base>
		<startingUnits>
			<workers>8</workers>
			<transports>1</transports>
			<unit type="Zergling">4</unit>
			<unit type="Hydralisk">1</unit>
		</startingUnits>
	</faction>

	<faction name="Queen of Blades">
		<race>Zerg</race>
		<base>Zerg Base</base>
		<startingUnits>
			<workers>7</workers>
			<transports>1</transports>
			<unit type="Zergling">3</unit>
			<unit type="Hydralisk">2</unit>
		</startingUnits>
	</faction>

	<faction name="Tassadar">
		<race>Protoss</race>
		<base>Protoss Base</base>
		<startingUnits>
			<workers>8</workers>
			<transports>1</transports>
			<unit type="Zealots">3</unit>
		</startingUnits>
	</faction>

	<faction name="Aldaris">
		<race>Protoss</race>
		<base>Protoss Base</base>
		<startingUnits>
			<workers>7</workers>
			<transports>1</transports>
			<unit type="Zealots">2</unit>
			<unit type="Dragoon">1</unit>
		</startingUnits>
	</faction>

</factions>
