=== Wiwiweb/Starcraft-Boardgame/res/xmlSchemas/planets.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="cardinal">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NORTH" />
			<xs:enumeration value="EAST" />
			<xs:enumeration value="SOUTH" />
			<xs:enumeration value="WEST" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="resource">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MINERALS" />
			<xs:enumeration value="GAS" />
			<xs:enumeration value="CONTROL" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="planets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="planet" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="entrance" maxOccurs="4" type="cardinal" />

							<xs:element name="area" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:int">
														<xs:attribute name="type" type="resource" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="unitLimit" type="xs:int" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />

					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

		<xs:unique name="planet">
			<xs:selector xpath="faction" />
			<xs:field xpath="@name" />
		</xs:unique>

	</xs:element>
</xs:schema>

=== Wiwiweb/Starcraft-Boardgame/res/data/planets.xml
<?xml version="1.0" encoding="UTF-8"?>
<planets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xmlSchemas/planets.xsd">

	<planet name="Pridewater">
		<entrance>NORTH</entrance>
		<entrance>EAST</entrance>
		<entrance>SOUTH</entrance>
		<area>
			<resource type="MINERALS">3</resource>
			<unitLimit>4</unitLimit>
		</area>
		<area>
			<resource type="GAS">2</resource>
			<unitLimit>4</unitLimit>
		</area>
		<area>
			<resource type="MINERALS">1</resource>
			<unitLimit>3</unitLimit>
		</area>
	</planet>

	<planet name="Chau Sara">
		<entrance>NORTH</entrance>
		<entrance>WEST</entrance>
		<area>
			<resource type="CONTROL">1</resource>
			<unitLimit>3</unitLimit>
		</area>
		<area>
			<resource type="GAS">1</resource>
			<unitLimit>4</unitLimit>
		</area>
		<area>
			<resource type="MINERALS">2</resource>
			<unitLimit>3</unitLimit>
		</area>
	</planet>

	<planet name="Braken">
		<entrance>NORTH</entrance>
		<entrance>WEST</entrance>
		<area>
			<resource type="CONTROL">1</resource>
			<unitLimit>4</unitLimit>
		</area>
		<area>
			<resource type="GAS">2</resource>
			<unitLimit>3</unitLimit>
		</area>
		<area>
			<resource type="MINERALS">1</resource>
			<unitLimit>2</unitLimit>
		</area>
	</planet>

	<planet name="Tarsonis">
		<entrance>NORTH</entrance>
		<entrance>EAST</entrance>
		<entrance>SOUTH</entrance>
		<area>
			<resource type="CONTROL">1</resource>
			<unitLimit>3</unitLimit>
		</area>
		<area>
			<resource type="GAS">2</resource>
			<unitLimit>4</unitLimit>
		</area>
		<area>
			<resource type="MINERALS">2</resource>
			<unitLimit>3</unitLimit>
		</area>
	</planet>

	<planet name="Abaddon">
		<entrance>EAST</entrance>
		<entrance>WEST</entrance>
		<area>
			<resource type="MINERALS">3</resource>
			<unitLimit>3</unitLimit>
		</area>
		<area>
			<resource type="CONTROL">1</resource>
			<unitLimit>4</unitLimit>
		</area>
	</planet>

</planets>
